#!/bin/sh
# gather.sh — collect all raw status data for a running headless agent
# in ONE read-only pass, printed as delimited sections for synthesis.
#
# Usage: gather.sh /path/to/repo
# Branch, kit dir and model are parsed from the repo's HANDOVER.md
# (regenerated by the loop at every launch, so always current).
#
# STRICTLY READ-ONLY: no checkout, no commits, no file writes into the
# repo, never creates STOP. Safe to run while the agent is mid-cycle.

REPO="${1:?usage: gather.sh /path/to/repo}"
cd "$REPO" || exit 1

section() { printf '\n===== %s =====\n' "$1"; }

# ---- configuration, from the loop's own operator card ----
section "CONFIG (from HANDOVER.md)"
if [ -f HANDOVER.md ]; then
  grep -E '^(Repo|Branch|Kit|Machine|Verification gate|Orchestrator model|Card generated):' HANDOVER.md
  BRANCH=$(sed -n 's/^Branch: //p' HANDOVER.md | head -1)
  KIT=$(sed -n 's/^Kit: //p' HANDOVER.md | head -1)
else
  echo "HANDOVER.md missing — is a headless agent set up in this repo?"
  BRANCH=""
  KIT=""
fi
BRANCH="${BRANCH:-agent-work}"
NOW=$(date)
echo "Now: $NOW"

# ---- is the loop alive? ----
section "SERVICE"
if [ "$(uname)" = "Darwin" ]; then
  LABEL="com.$(id -un).claude-agent"
  launchctl print "gui/$(id -u)/$LABEL" 2>/dev/null | grep -E 'state|pid' \
    || echo "launchd service $LABEL not loaded"
else
  systemctl --user is-active claude-agent 2>/dev/null \
    || echo "systemd service claude-agent not active"
  systemctl --user status claude-agent 2>/dev/null | head -5
fi

section "HEARTBEAT (last 25 loop status lines)"
if [ "$(uname)" = "Darwin" ] && [ -n "$KIT" ] && [ -f "$KIT/launchd.out.log" ]; then
  tail -25 "$KIT/launchd.out.log"
else
  journalctl --user -u claude-agent -n 25 --no-pager 2>/dev/null \
    || echo "no heartbeat source found"
fi

# ---- repo state files ----
section "PHASE";      cat PHASE 2>/dev/null || echo "missing"
section "STOP";       [ -f STOP ] && echo "STOP FILE PRESENT (loop is/was told to exit)" || echo "absent (normal)"
section "GOAL.md";    cat GOAL.md 2>/dev/null || echo "missing"
section "PROGRESS.md (last 60 lines)"; tail -60 PROGRESS.md 2>/dev/null || echo "missing"
section "PROGRESS.md (first entry, for run start date)"; head -8 PROGRESS.md 2>/dev/null
section "ATTENTION.md"; cat ATTENTION.md 2>/dev/null || echo "missing"
section "BLOCKED.md";   cat BLOCKED.md 2>/dev/null || echo "missing"

# ---- git evidence (no checkout: read refs directly) ----
section "GIT SUMMARY (branch: $BRANCH)"
BASE=$(git merge-base main "$BRANCH" 2>/dev/null || git merge-base master "$BRANCH" 2>/dev/null)
[ -z "$BASE" ] && echo "note: no main/master base found; counts cover the whole branch history"
echo "total commits on branch since base: $(git rev-list --count ${BASE:+$BASE..}$BRANCH 2>/dev/null)"
echo "WIP-CHECKPOINT commits (unverified): $(git log --oneline --grep=WIP-CHECKPOINT "$BRANCH" 2>/dev/null | wc -l | tr -d ' ')"
echo "last commit: $(git log -1 --format='%ci  %s' "$BRANCH" 2>/dev/null)"
echo "--- last 20 commits ---"
git log --oneline -20 "$BRANCH" 2>/dev/null
echo "--- diffstat since base ---"
[ -n "$BASE" ] && git diff --stat "$BASE" "$BRANCH" 2>/dev/null | tail -12

# ---- failure evidence ----
section "RECENT CYCLE ERRORS (last 3 non-empty .err files)"
if [ -d logs ]; then
  # shellcheck disable=SC2012
  for f in $(ls -t logs/cycle-*.err 2>/dev/null | head -20); do
    [ -s "$f" ] || continue
    echo "--- $f ---"; tail -8 "$f"
    n=$((${n:-0}+1)); [ "$n" -ge 3 ] && break
  done
  [ -z "${n:-}" ] && echo "no non-empty error files (good)"
else
  echo "no logs/ directory"
fi

# ---- consumption ----
section "USAGE"
if [ -n "$KIT" ] && [ -x "$KIT/usage.sh" ]; then
  "$KIT/usage.sh" "$REPO" "$BRANCH"
else
  echo "usage.sh not found in kit dir ($KIT)"
fi

section "END"
